#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

PASSWD_FILE=/home/pi/.setup/passwd.conf
CONFIG_FILE=/opt/openmuc/conf/emoncms.conf

if [ -e $CONFIG_FILE ]; then
    emoncms_address_key="address"
    emoncms_address_value=`grep -A11 -P "^\[HTTP\]$" $CONFIG_FILE | grep -m1 "$emoncms_address_key.*=" |\
                           sed "s/.*$emoncms_address_key.*=//g" | sed -r "s/\s+//g"`
    db_set emoncms/address "$emoncms_address_value"

    emoncms_auth_key="authentication"
    emoncms_auth_value=`grep -A11 -P "^\[HTTP\]$" $CONFIG_FILE | grep -m1 "$emoncms_auth_key.*=" |\
                        sed "s/.*$emoncms_auth_key.*=//g" | sed -r "s/\s+//g"`
    if [ "$emoncms_auth_value" != "API_KEY" ]; then
        db_set emoncms/authentication "$emoncms_auth_value"
    fi

    mysql_host_key="host"
    mysql_host_value=`grep -A11 -P "^\[SQL\]$" $CONFIG_FILE | grep -m1 "$mysql_host_key.*=" |\
                      sed "s/.*$mysql_host_key.*=//g" | sed -r "s/\s+//g"`
    db_set openmuc/mysql_host "$mysql_host_value"

    mysql_port_key="port"
    mysql_port_value=`grep -A11 -P "^\[SQL\]$" $CONFIG_FILE | grep -m1 "$mysql_port_key.*=" |\
                      sed "s/.*$mysql_port_key.*=//g" | sed -r "s/\s+//g"`
    db_set openmuc/mysql_port "$mysql_port_value"

    mysql_database_key="database"
    mysql_database_value=`grep -A11 -P "^\[SQL\]$" $CONFIG_FILE | grep -m1 "$mysql_database_key.*=" |\
                          sed "s/.*$mysql_database_key.*=//g" | sed -r "s/\s+//g"`
    if [ "$mysql_database_value" != "MYSQL_DATABASE" ]; then
        db_set openmuc/mysql_database "$mysql_database_value"
    fi

    mysql_user_key="user"
    mysql_user_value=`grep -A11 -P "^\[SQL\]$" $CONFIG_FILE | grep -m1 "$mysql_user_key.*=" |\
                      sed "s/.*$mysql_user_key.*=//g" | sed -r "s/\s+//g"`
    if [ "$mysql_user_value" != "MYSQL_USER" ]; then
        db_set openmuc/mysql_user "$mysql_user_value"
    fi

    mysql_password_key="password"
    mysql_password_value=`grep -A11 -P "^\[SQL\]$" $CONFIG_FILE | grep -m1 "$mysql_password_key.*=" |\
                          sed "s/.*$mysql_password_key.*=//g" | sed -r "s/\s+//g"`
    if [ "$mysql_password_value" != "MYSQL_PASSWORD" ]; then
        db_set openmuc/mysql_password "$mysql_password_value"
    fi
fi

db_input medium emoncms/address || true
if [ -z "$emoncms_auth_value" ] || [ "$emoncms_auth_value" = "API_KEY" ]; then
    db_input critical emoncms/authentication || true
else
    db_input medium emoncms/authentication || true
fi

db_input low openmuc/mysql_host || true
db_input low openmuc/mysql_port || true
db_input medium openmuc/mysql_database || true
db_input medium openmuc/mysql_user || true

db_go || true
db_get openmuc/mysql_user
if [ $RET != $mysql_user_value ]; then
    mysql_user_value=$RET
    mysql_password_value=""
fi
if [ -f $PASSWD_FILE ] && grep -A3 -P '^\[MySQL\]$' $PASSWD_FILE | grep -m1 -q "$mysql_user_value"; then
    mysql_password_value=`grep -A3 -P "^\[MySQL\]$" $PASSWD_FILE | grep -m1 "$mysql_user_value:" |\
                          sed "s/$mysql_user_value://g" | sed -r "s/\s+//g"`
    db_set openmuc/mysql_password "$mysql_password_value"
fi
if [ -z "$mysql_password_value" ] || [ "$mysql_password_value" = "MYSQL_PASSWORD" ]; then
    if dpkg -l | grep -e pwgen >/dev/null 2>&1; then
        mysql_password_value=`pwgen -s1 32`
        db_set openmuc/mysql_password "$mysql_password_value"
        db_input medium openmuc/mysql_password || true
    else
        db_input high openmuc/mysql_password || true
    fi
else
    db_input medium openmuc/mysql_password || true
fi
db_go || true
